---
name: test

"on":
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  tox:
    name: ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - py310-django52
          - py311-django52
          - py312-django60
          - py313-django60
          - py314-django60
          - dev
          - mypy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run tox
        run: uvx --with tox-uv tox -e "${{ matrix.env }}"

      - name: Upload coverage to Codecov
        if: ${{ (success() || failure()) && matrix.env != 'mypy' }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.env }}
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ (success() || failure()) && matrix.env != 'mypy' }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          flags: ${{ matrix.env }}
          fail_ci_if_error: true
